=== PapiHack/EvalProject/Exo/Meissa/TP3/exo3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<!-- Déclarations des éléments de type simple -->
	
	<xsd:element name="titre" type="xsd:string"/>
	<xsd:element name="auteur" type="xsd:string"/>
	<xsd:element name="pages" type="xsd:string"/>
	<xsd:element name="editeur" type="xsd:string"/>
	<xsd:element name="lieuEdition" type="xsd:string"/>
	<xsd:element name="lieuImpression" type="xsd:string"/>
	<xsd:element name="ISBN" type="xsd:string"/>
	<xsd:element name="nomJournal" type="xsd:string"/>
	<xsd:element name="anneePublication" type="xsd:string"/>
	<xsd:element name="numéroJournal" type="xsd:string"/>
	<xsd:element name="avis" type="xsd:string"/>
	
	<!-- Déclarations des éléments de type complexe -->
	
	<xsd:element name="infosEdition">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="editeur"/>
				<xsd:element ref="lieuEdition"/>
				<xsd:element ref="lieuImpression"/>
				<xsd:element ref="ISBN"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="tome">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="pages"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="tomes">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tome" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="livre">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="titre"/>
				<xsd:element ref="auteur" maxOccurs="unbounded"/>
				<xsd:element ref="tomes"/>
				<xsd:element ref="infosEdition"/>
				<xsd:element ref="avis" minOccurs="0" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="infosPublication">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nomJournal"/>
				<xsd:element ref="pages"/>
				<xsd:element ref="anneePublication"/>
				<xsd:element ref="numéroJournal"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="article">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="titre"/>
				<xsd:element ref="auteur" minOccurs="1" maxOccurs="unbounded"/>
				<xsd:element ref="infosPublication"/>
				<xsd:element ref="avis" minOccurs="0" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="biblio">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="livre"/>
				<xsd:element ref="article"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== PapiHack/EvalProject/Exo/Meissa/TP3/exo3.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="exo3.xsd">
  <livre>
    <titre>Coder proprement (Clean Code: a handbook of agile softwarecraftsmanship)</titre>
    <auteur>Robert C. Martin</auteur>
    <auteur>Michael C. Feathers</auteur>
    <auteur>Jeffrey J. Langr</auteur>
    <auteur>James W. Grenning</auteur>
    <auteur>Timothy R. Ottinger</auteur>
    <auteur>Brett L. Schuchert</auteur>
    <auteur>Kevin Dean Wampler</auteur>
    <tomes>
      <tome>
        <pages>481</pages>
      </tome>
    </tomes>
    <infosEdition>
      <editeur>Pearson Education France</editeur>
      <lieuEdition>Paris</lieuEdition>
      <lieuImpression>47 bis, rue des Vinaigriers</lieuImpression>
      <ISBN>978-0-13-235088-2</ISBN>
    </infosEdition>
      <avis>Excellent livre</avis>
  </livre>
</biblio>
