=== PapiHack/EvalProject/Exo/Meissa/parc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<!-- Déclarations des éléments de type simple -->

<xs:element name="nom" type="xs:string"/>
<xs:element name="prenom" type="xs:string"/>
<xs:element name="telephone" type="xs:string"/>
<xs:element name="cin" type="xs:string"/>
<xs:element name="marque" type="xs:string"/>
<xs:element name="modele" type="xs:string"/>
<xs:element name="immatriculation" type="xs:string"/>
<xs:element name="proprietaire" type="xs:string"/>

<!-- Déclarations des éléments de type complexe -->

<xs:element name="telephones">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="telephone" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="personne">
  <xs:complexType>
    <xs:sequence>
      <xs:element  ref="nom"/>
      <xs:element  ref="prenom"/>
      <xs:element  ref="cin"/>
      <xs:element ref="telephones"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="vehicule">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="marque"/>
      <xs:element ref="modele"/>
      <xs:element ref="immatriculation"/>
      <xs:element ref="proprietaire"/>
    </xs:sequence>  
  </xs:complexType>
</xs:element>

  <xs:element name="parcAutomobile">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="personne" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element ref="vehicule" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    
    <!-- Définition de la contrainte référentielle d'un  véhicule à une personne (relation de propriété) -->
    
      <xs:key name="proprio">
        <xs:selector xpath="personne"/>
        <xs:field xpath="cin"/>
    </xs:key>
    
    <xs:keyref name="vehiculeProprio" refer="proprio">
      <xs:selector xpath="vehicule"/>
      <xs:field xpath="proprietaire"/>
    </xs:keyref>
    
  </xs:element>
  
</xs:schema>

=== PapiHack/EvalProject/Exo/Meissa/parc.xml
<?xml version="1.0" encoding="UTF-8"?>
<parcAutomobile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="parc.xsd">
  <personne>
    <nom>Mbaye</nom>
    <prenom>Papi</prenom>
    <cin>0119942010</cin>
    <telephones>
      <telephone>779391561</telephone>
      <telephone>762719971</telephone>
    </telephones>
  </personne>
  
    <personne>
    <nom>Mbaye</nom>
    <prenom>Derguene</prenom>
    <cin>0119972010</cin>
    <telephones>
      <telephone>771322302</telephone>
      <telephone>761377239</telephone>
    </telephones>
  </personne>
  
    <personne>
    <nom>Kanouté</nom>
    <prenom>Alioune Harouna</prenom>
    <cin>0119982010</cin>
    <telephones>
      <telephone>771322302</telephone>
      <telephone>761377239</telephone>
    </telephones>
  </personne>
  
  <vehicule>
    <marque>Toyota</marque>
    <modele>RAV4</modele>
    <immatriculation>DK1994</immatriculation>
    <proprietaire>0119972010</proprietaire>
  </vehicule>
  
    <vehicule>
    <marque>Mercedes</marque>
    <modele>AMG64</modele>
    <immatriculation>DK1997</immatriculation>
    <proprietaire>0119942010</proprietaire>
  </vehicule>
  
    <vehicule>
    <marque>Audi</marque>
    <modele>A7</modele>
    <immatriculation>DK8294</immatriculation>
    <proprietaire>0119982010</proprietaire>
  </vehicule>
  
  <vehicule>
    <marque>Porche</marque>
    <modele>Cayenne</modele>
    <immatriculation>DK199</immatriculation>
    <proprietaire>0119942010</proprietaire>
  </vehicule>
</parcAutomobile>
